import Head from 'next/head'
import Header from '../components/Header'
import Navbar from '../components/Navbar'
import Results from '../components/Results'
import requests from '../utils/requests'

export default function Home ({ results }) {
  console.log(results)

  return (
    <div>
      <Head>
        <title>MoviesIo 👾</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://cdn.iconscout.com/icon/premium/png-256-thumb/movie-60-165251.png" />
      </Head>

      <main>
        <Header />
        <Navbar />
        <Results results={results}/>
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  const genre = context.query.genre

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then(res => res.json())

  return {
    props: {
      results: request.results,
    }
  }
}
